apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "addok.redis.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "addok.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "addok.redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "etalab/addok-redis"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
