apiVersion: v1
kind: Service
metadata:
  name: {{ include "addok.redis.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "addok.redis.selectorLabels" . | nindent 4 }}
