apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vtl-lab.fullname" . }}
  labels:
    {{- include "vtl-lab.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vtl-lab.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "vtl-lab.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
