apiVersion: v1
kind: Service
metadata:
  name: {{ include "vtl-lab.fullname" . }}
  labels: {{- include "vtl-lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "vtl-lab.selectorLabels" . | nindent 4 }}
